server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.11:3306/test?useSSL=false&serverTimezone=GMT%2b8&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    database: 0
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
